name: creca_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # design
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.4

  # ui
  flutter_credit_card: ^3.0.7

  # network
  http: ^1.1.0
  freezed_annotation: ^2.4.1

  # storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.2.1
  
  # other
  uuid: ^3.0.7
  path_provider: ^2.1.1
  intl: ^0.18.0
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.3.1
  isar_generator: ^3.1.0+1
  freezed: ^2.4.1
  json_serializable: ^6.7.1

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

